name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${immich_version}
    volumes:
      - ${immich_upload_location}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${immich_external_libraries}:/mnt/4tb/immich/external_libraries
#    env_file:
#      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: on-failure

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${immich_version}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${immich_version}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
#    env_file:
#      - .env
    restart: on-failure

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${immich_db_password}
      POSTGRES_USER: ${immich_db_username}
      POSTGRES_DB: ${immich_db_name}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${immich_db_location}:/var/lib/postgresql/data
    restart: on-failure
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
