services:
    ntfy:
        volumes:
            - ${CONFIG_STORAGE_LOCATION}/ntfy:/var/cache/ntfy
            - ${CONFIG_STORAGE_LOCATION}/ntfy/user.db:/var/lib/ntfy/user.db
            - ${CONFIG_STORAGE_LOCATION}/nginx/server.yml:/var/lib/ntfy/server.yml
        ports:
            - 8067:80
        container_name: ntfy
        environment:
            - TZ=EST
        stdin_open: true
        tty: true
        restart: unless-stopped
        image: binwiederhier/ntfy
        command: serve --cache-file /var/cache/ntfy/cache.db
