services:
    uptime-kuma:
        restart: always
        ports:
            - 3001:3001
        volumes:
            - ${CONFIG_STORAGE_LOCATION}/uptime-kuma:/app/data
        container_name: uptime-kuma
        image: louislam/uptime-kuma
