services:
    home-assistant:
        ports:
          - 8124:8123
        container_name: homeassistant
        privileged: true
        volumes:
            - ${CONFIG_STORAGE_LOCATION}/homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus
        restart: unless-stopped
        environment:
            - TZ=America/New_York
        image: ghcr.io/home-assistant/home-assistant:stable
        labels:
            - "com.centurylinklabs.watchtower.enable=false" # disable auto updates via watchtower
