services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONFIG_STORAGE_LOCATION}/syncthing/config:/config
      - ${CONFIG_STORAGE_LOCATION}/syncthing/syncthing:/var/syncthing
      - ${syncthing_dir}:/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
