services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=Etc/UTC
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${CONFIG_STORAGE_LOCATION}/crafty/backups:/crafty/backups
        - ${CONFIG_STORAGE_LOCATION}/crafty/logs:/crafty/logs
        - ${CONFIG_STORAGE_LOCATION}/crafty/servers:/crafty/servers
        - ${CONFIG_STORAGE_LOCATION}/crafty/config:/crafty/app/config
        - ${CONFIG_STORAGE_LOCATION}/crafty/import:/crafty/import
