services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8181:8080" # webapp
      - "8085:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${CONFIG_STORAGE_LOCATION}/scrutiny/config:/opt/scrutiny/config
      - ${CONFIG_STORAGE_LOCATION}/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
